version: '3'
 
services:
  php:
    image: php:apache
    container_name: php
    links:
      - db
    ports:
      - 8081:80
    volumes:
      - /home/fhernandez/Documents/Cursos/curso-php/tarea2/docker-compose/phpdata:/var/www/html/
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - /home/fhernandez/Documents/Cursos/curso-php/tarea2/docker-compose/dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80

